### ISSUE TITLE
Bug with Zenmode Pluging? Inserting multiple times

### ISSUE THREAD

**Issue by zach-is-my-name** [kiyoon/telescope-insert-path.nvim#1] opened 2023-01-20 20:13 UTC
Hi I love your plugin, I'm not sure why it's not global sensation.... (are people really content to look up relative paths for all their imports, temporarily memorize them, then type them?  maybe they have sufficiently advanced autocomplete)

Anyway, bug with with folke/zen-mode.nvim... 
I'd understand completely if its a 'won't fix' (it works when not in ZenMode) but maybe it's simple or you consider this particular zen-mode plugin popular enough to take a look at it... 

![telescope-path](https://user-images.githubusercontent.com/16063092/213794942-81e34701-d648-46b7-a05f-e7af224ad2b1.gif)

**Comment by zach-is-my-name** [comment] 2023-01-20 21:06
Actually it's happening outside of Zenmode as well...  what's weird is that after the bad insertion, when I type 'u' for undo, the editor only reverses the insert on the line it's meant to be... not the errant insertion

**Comment by kiyoon** [comment] 2023-01-21 01:23
Hi, thanks for using my plugin! You're right, I think `i` mode is bugged. I'll take a look into this soon. Thanks for reporting!

**Comment by kiyoon** [comment] 2023-01-21 16:32
I think it should be fixed with the latest commit (7eed4eecea2ae6e635892d66b7010a5da0ac8384)

**Comment by zach-is-my-name** [comment] 2023-01-21 18:34
Sorry, not on my end... Ran :PlugUpdate from vim plug, to update and sourced the config)
![Screenshot from 2023-01-21 13-30-54](https://user-images.githubusercontent.com/16063092/213881944-a2178463-6a7f-4b8b-8683-a1d703d93fa8.png)

**Comment by kiyoon** [comment] 2023-01-21 20:26
@zach-is-my-name I can't reproduce.. It works well on my side.

**Comment by zach-is-my-name** [comment] 2023-01-21 20:32
Thanks.  I may investigate myself, until then I'm successfully able put the cursor on the last line of the file, insert, and then cut & paste

**Comment by kiyoon** [comment] 2023-01-21 20:47
Maybe the plugin hasn't been updated properly? Let me know how I can reproduce if you find out how to.

**Comment by kiyoon** [comment] 2023-07-31 12:09
Closing due to inactivity. Seems alright to me.

**Closed as completed by kiyoon** 2023-07-31 12:09 UTC
